### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [chougousui/complete-lastf#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by chougousui** [comment]
Hi,

Thank you for reaching out and for considering adding my project to
awesome-zsh-plugins!

I've added a license file to the repository, and I also took the
opportunity to include some internationalization (i18n) updates for broader
accessibility.

Feel free to check it out, and let me know if there's anything else I can
do!

Best regards,

Joe Block ***@***.***> 于2024年10月12日周六 23:58写道：
